# Generated by Django 5.2.7 on 2025-11-24 07:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='buildinginfo',
            options={'ordering': ['name'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='findusposter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Find Us Media', 'verbose_name_plural': 'Find Us Media'},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'ordering': ['section'], 'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Contents'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='buildinginfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='buildinginfo',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='announcement_active',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='announcement_text',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='site_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='welcome_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='welcome_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='welcome_title',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='buildinginfo',
            name='code',
            field=models.CharField(blank=True, help_text='Short code for the building (e.g., MAIN, GYM, LIB)', max_length=10, null=True, unique=True, verbose_name='Building Code'),
        ),
        migrations.AddField(
            model_name='buildinginfo',
            name='floor_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Floors'),
        ),
        migrations.AddField(
            model_name='buildinginfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lrn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AddField(
            model_name='findusposter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='content',
            field=models.TextField(blank=True, help_text='Content for this section (can include HTML)', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='section',
            field=models.CharField(blank=True, help_text='A unique identifier for this section (e.g., "welcome", "about", "contact")', max_length=100, null=True, unique=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(blank=True, help_text='The title to display for this section', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('building_created', 'Building Created'), ('building_updated', 'Building Updated'), ('building_deleted', 'Building Deleted'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('other', 'Other')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buildinginfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='buildinginfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='buildinginfo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Building Name'),
        ),
        migrations.AlterField(
            model_name='buildinginfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Upload a poster image (JPEG, PNG, etc.)', null=True, upload_to='posters/', verbose_name='Poster Image'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, etc.)', null=True, upload_to='videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='findusposter',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Or enter a YouTube video URL', null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=20, verbose_name='Theme')),
                ('font_size', models.PositiveSmallIntegerField(default=14, help_text='Base font size in pixels', verbose_name='Font Size')),
                ('dashboard_layout', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View')], default='grid', max_length=20, verbose_name='Dashboard Layout')),
                ('accent_color', models.CharField(default='#4a6baf', help_text='Primary color for the UI in hex format (e.g., #4a6baf)', max_length=7, verbose_name='Accent Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['user__username'],
            },
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
