# Generated by Django 5.2.7 on 2025-11-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_alter_activitylog_options_alter_buildinginfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', help_text='Font size preference (small, medium, large)', max_length=10, verbose_name='Font Size'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('sunset', 'Sunset')], default='light', max_length=20, verbose_name='Theme'),
        ),
    ]
