# Generated by Django 4.2 on 2025-11-01 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapapp', '0002_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField(help_text='Latitude for map location')),
                ('longitude', models.FloatField(help_text='Longitude for map location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('office', 'Office'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mapapp.building')),
            ],
            options={
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 10-Newton, 11-Einstein', max_length=50)),
                ('grade_level', models.PositiveIntegerField(help_text='Grade level (e.g., 10, 11, 12)')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_class', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('units', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='mapapp.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('07:30-08:30', '7:30 AM - 8:30 AM'), ('08:30-09:30', '8:30 AM - 9:30 AM'), ('09:30-10:30', '9:30 AM - 10:30 AM'), ('10:30-11:30', '10:30 AM - 11:30 AM'), ('11:30-12:30', '11:30 AM - 12:30 PM'), ('12:30-13:30', '12:30 PM - 1:30 PM'), ('13:30-14:30', '1:30 PM - 2:30 PM'), ('14:30-15:30', '2:30 PM - 3:30 PM'), ('15:30-16:30', '3:30 PM - 4:30 PM'), ('16:30-17:30', '4:30 PM - 5:30 PM')], max_length=20)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='mapapp.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='mapapp.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='mapapp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'time_slot'],
                'unique_together': {('day', 'time_slot', 'section', 'academic_year')},
            },
        ),
    ]
