# Generated by Django 4.2 on 2025-11-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapapp', '0006_initial_schedule_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '🌞 Light'), ('dark', '🌙 Dark'), ('sunset', '🌇 Sunset')], default='light', max_length=10)),
                ('accent_color', models.CharField(default='#ff6b9e', max_length=7)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('dashboard_layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
