# Generated by Django 4.2 on 2025-11-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adviser_name',
            field=models.CharField(blank=True, help_text="Teacher's name as adviser", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Building where teacher is assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='mapapp.building'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_level',
            field=models.PositiveIntegerField(blank=True, help_text='Grade level taught (e.g., 10, 11, 12)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strand',
            field=models.CharField(blank=True, help_text='Academic strand (e.g., ABM, STEM, HUMSS)', max_length=50, null=True),
        ),
    ]
