# Generated by Django 4.2 on 2025-11-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0009_userprofile_adviser_name_userprofile_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adviser_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='building',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='strand',
        ),
    ]
