# Generated by Django 4.2 on 2025-11-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0010_remove_userprofile_adviser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='schedules_last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time schedules were modified for this section'),
        ),
    ]
