# Generated by Django 4.2 on 2025-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0011_section_schedules_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes about the room'),
        ),
        migrations.AddField(
            model_name='room',
            name='assigned_staff',
            field=models.CharField(blank=True, help_text='Assigned teacher, staff, or department', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.JSONField(blank=True, default=list, help_text='List of available facilities'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, help_text='Air conditioned'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_accessible',
            field=models.BooleanField(default=False, help_text='Wheelchair accessible'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_faculty_only',
            field=models.BooleanField(default=False, help_text='Faculty/staff only access'),
        ),
        migrations.AddField(
            model_name='room',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='e.g., 8:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='purpose',
            field=models.CharField(blank=True, help_text='Specific purpose or function of the room', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('office', 'Office'), ('auditorium', 'Auditorium'), ('library', 'Library'), ('gym', 'Gymnasium'), ('cafeteria', 'Cafeteria'), ('restroom', 'Restroom'), ('storage', 'Storage'), ('other', 'Other')], max_length=50),
        ),
    ]
