# Generated by Django 4.2 on 2025-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0012_room_additional_notes_room_assigned_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='building_images/')),
                ('operating_hours', models.CharField(default='Monday - Friday: 7:00 AM - 6:00 PM', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='section',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='section',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='adviser',
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
