# Generated by Django 4.2 on 2025-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0013_buildinginfo_remove_notification_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
