# Generated by Django 4.2 on 2025-11-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0014_userpreferences_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindUsPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Find Us', max_length=100)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='find_us_posters/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
