# Generated by Django 4.2 on 2025-11-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0015_findusposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='FINDIT - School Map', max_length=100)),
                ('welcome_title', models.CharField(default='School Campus Map', max_length=200)),
                ('welcome_subtitle', models.CharField(default='Welcome back, {username}!', max_length=300)),
                ('welcome_description', models.TextField(default='Navigate your campus with ease - Find buildings, rooms, and more. Use the interactive map to explore facilities and get directions.')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='home_content/')),
                ('announcement_text', models.TextField(blank=True, help_text='Important announcements to display on home page')),
                ('announcement_active', models.BooleanField(default=False)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home_content/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
                'ordering': ['-updated_at'],
            },
        ),
    ]
