# Generated by Django 4.2 on 2025-11-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0016_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='findusposter',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, etc.)', null=True, upload_to='find_us_videos/'),
        ),
        migrations.AddField(
            model_name='findusposter',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', null=True),
        ),
    ]
