# Generated by Django 5.2.7 on 2025-11-22 16:18

import mapapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0017_findusposter_video_file_findusposter_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=mapapp.models.user_profile_picture_path),
        ),
    ]
