# Generated by Django 5.2.7 on 2025-11-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0019_activitylog'),
    ]

    operations = [
    ]
